export const GET_CANDIDATES = 'GET_CANDIDATES';
export const SORT_CANDIDATES = 'SORT_CANDIDATES';
export const FILTER_CANDIDATES = 'FILTER_CANDIDATES';
export const UPDATE_CANDIDATE_STATUS = 'UPDATE_CANDIDATE_STATUS';